### ISSUE TITLE
waveform-data.min throws "Uncaught Error: Zoom level 32 too low, minimum: 512"

### ISSUE THREAD

**Issue by david-wb** [bbc/peaks.js#104]
Why is this happening? I followed the instructions in the readme.md exactly.

**Comment by oncletom** [comment]
Hello guys, and sorry for the delay! I have not realised this issue (and others) have been queued for such a long time :-(

So yes the problem arises when an audio file is shorter than the available displayed duration in the zoomView.

@Acubed pointed the right option to overcome the problem. Maybe peaks could automatically adjust the initial scale option based on the audio length. Feel free to abund, reject or implement the idea :-)

**Comment by bitwit** [comment]
It's not just about the audio file length, but the Zoom levels you have configured in your peaks instance. I.e. if you have your lowest zoom level as '128' and the default scale is '512', any file you try to load would fail because it starts by trying to render at that lowest zoom level, which is below the minimum.

**Comment by wader** [comment]
@Acubed thanks

**Comment by HopeXKelvin** [comment]
I also have this problem today. At last ,I found out that this is not because the audio file is to short. The problem was happened because when I create waveform data files from source audio file,that I do not set the appropriate arguments.
Such as next pic:
![image](https://cloud.githubusercontent.com/assets/12066469/19346950/bc8d7486-9178-11e6-9fed-fe9cdff6c50a.png)

The red part is the point.When I set this argument to 8, the problem was gone.And this problem happened when the audio file is short.So the solution to solve this problems is set the argument after "-z" as smaller as possible ( finally I set it to 8).Also ,I change the options to use peakjs. Like next pic:
![image](https://cloud.githubusercontent.com/assets/12066469/19347032/5cba9cc2-9179-11e6-9456-d8b7cf72042d.png)

**Comment by wemiao** [comment]
Hi guys, I ran into this zoomLevel too low issue today.  I noticed several commentators on this thread talking about @acubed having an answer, but I don't see any acubed in this thread.  Could you tell me exactly what I need to set?  Do I need to use the audiowaveform library or can I read raw wav files directly?  Obviously the latter would be more convenient.

![zoomlevel](https://user-images.githubusercontent.com/16315883/30300240-772f8168-9708-11e7-95a9-463c01bcd39b.PNG)

Thanks,
William

**Comment by awwright** [comment]
@wemiao That'd be me. See https://github.com/bbc/peaks.js/issues/104#issuecomment-68095563

**Comment by wemiao** [comment]
Thanks @awwright.  I just tried this, and I got this message.  After changing it, it seemed to work.  So I guess the answer has changed from then until now just a bit.
![errorscale](https://user-images.githubusercontent.com/16315883/30301158-d544ce16-970d-11e7-8b5b-a8e1f202c609.PNG)


Thanks,
William

**Comment by mwilde345** [comment]
adding the waveformBuilderOptions doesn't seem to be working. Where do you add it?
I am putting it in the peaks options.
@awwright

**Comment by chrisn** [comment]
@mwilde345 The default minimum scale/zoomLevel value is 512. If you want to use a lower value than this, you'll need to set the `waveformBuilderOptions`. Here's an example:
```javascript
var audioContext = new AudioContext();

var peaksInstance = Peaks.init({
  container: document.getElementById('waveform-container'),
  mediaElement: document.getElementById('audio'),
  audioContext: audioContext,

  waveformBuilderOptions: {
    scale: 128
  },
  zoomLevels: [128, 256, 512, 1024, 2048]
});
```

I'll look at improving the interface to make this more straightforward in a future version.

**Comment by chrisn** [comment]
If you're using [audiowaveform](https://github.com/bbc/audiowaveform) to generate precomputed waveform data files, you should set the `-z` option to the minimum zoom level you want to display.

For example, if you want the minimum zoom to be 128 samples/pixel, you should invoke audiowaveform like this:

```bash
audiowaveform -i example.mp3 -o example.dat -b 8 -z 128
```
or
```bash
audiowaveform -i example.mp3 -o example.json -b 8 -z 128
```

and then initialise Peaks.js like this:

```
var peaksInstance = Peaks.init({
  container: document.getElementById('waveform-container'),
  mediaElement: document.getElementById('audio'),
  dataUri: {
    arraybuffer: '/example.dat',
    json: '/example.json'
  },
  zoomLevels: [128, 256, 512, 1024, 2048]
});
```
The lowest value in the `zoomLevels` array should be the same as the audiowaveform `-z` option value.

Note that the default zoom level in audiowaveform is 256 samples/pixel, whereas in Peaks.js it's 512. We should probably make this consistent or, preferably, make Peak.js do the right thing by default...

**Comment by mwilde345** [comment]
@chrisn excellent answer thank you. I was missing the zoomLevels key

**Comment by mwilde345** [comment]
sorry @chrisn for the noob question, but I can't seem to pull in this new update for the life of me.
npm update
npm install --save peaks.js
npm install --save git+https://git@github.com/bbc/peaks.js.git
still gives me the old versions

**Comment by manoharreddyporeddy** [comment]
@chrisn  @awwright  @bitwit 

Please allow zoom level 0 too.

Some audio are less than 0 seconds. And these can be 1st audio.
In this case Peaks.init fails, and never recovers.

**Comment by Novaras** [comment]
Any movement on this?

`waveformBuilderOptions` doesn't seem to do anything at all!

Err:
```

**Comment by chrisn** [comment]
I should really write a proper tutorial guide on the zoom level settings...

> Any movement on this?
>
> `waveformBuilderOptions` doesn't seem to do anything at all!

You didn't say which version you're using, but I recommend updating to the latest 0.21.0 release. The `waveformBuilderOptions` option was removed back in 0.13.0 last year.
 
> `48000` seems to be the sample rate. I'm unsure what `6992` refers to.

6992 is the zoom level that Peaks.js has calculated is needed to fit your waveform into the overview container.

It's not clear why it says the minimum is 48000, suggests a possible problem with the waveform JSON file you're using.

> I basically can't load short files in any format into peaks. Do they _have_ to be genned by `audiowaveform`? It would be massively more convenient if not.

You can use the `webAudio` option to generate the waveforms in the browser. See [this example](https://github.com/bbc/peaks.js/blob/master/demo/webaudio.html#L236).

> Note that the proper error handlers don't catch or emit the error given: it comes from `peaks.js`

You should find this fixed in 0.21.0.

**Comment by Novaras** [comment]
Have just bumped from `0.20.0` to `0.21.0`. Now I don't get rogue errors anymore. 👍 
That said, my core issue of mystery numbers is still present.

Where is `48000` (often `44100`) coming from? I'm fetching the waveform from the server, and it's saved into the server like this:

`/usr/local/bin/audiowaveform -i $this->inputPath -o $this->outputPath --pixels-per-second $this->pixelsPerSecond -b 8`
Where `$pixelsPerSecond` is `10` unless overridden. Does anything glare out to you as being erroneous?

Thanks for the quick responses!

**Comment by chrisn** [comment]
I expect 48000 and 44100 are the audio sample rate. The value Peaks.js uses is the waveform scale, which is a number of samples per pixel. What does your JSON file contain? Using `--pixels-per-second 10`, I get something like this:
```json
{"version":2,"channels":1,"sample_rate":44100,"samples_per_pixel":4410,
 "bits":8,"length":2,"data":[-87,87,-8,12]}
```
